from __future__ import annotations

import pytest
from django.db import IntegrityError

from apps.users.models import Role, User

pytestmark = pytest.mark.django_db


def test_user_email_normalized_and_login_field():
    u = User.objects.create_user("Mixed@Case.COM", "StrongPassw0rd!23")
    assert u.email == "mixed@case.com"
    assert User.USERNAME_FIELD == "email"


def test_superuser_is_super_admin_role():
    u = User.objects.create_superuser("s@x.com", "StrongPassw0rd!23")
    assert u.role == Role.SUPER_ADMIN
    assert u.is_super_admin and u.is_admin_level and u.can_publish()


def test_role_helpers():
    editor = User.objects.create_user("e@x.com", "x", role=Role.EDITOR)
    seo = User.objects.create_user("seo@x.com", "x", role=Role.SEO_MANAGER)
    cm = User.objects.create_user("c@x.com", "x", role=Role.CONTENT_MANAGER)
    assert editor.can_publish() and not editor.manages_seo()
    assert seo.manages_seo() and not seo.can_publish()
    assert not cm.can_publish() and not cm.manages_seo()


def test_duplicate_email_rejected():
    User.objects.create_user("dup@x.com", "x")
    with pytest.raises(IntegrityError):
        User.objects.create_user("dup@x.com", "y")


def test_published_queryset_filters_status(published_project):
    from apps.projects.models import Project
    Project.objects.create(slug="draft", title="Draft", status="draft")
    pubs = Project.objects.published()
    assert published_project in pubs
    assert pubs.count() == 1


def test_testimonial_rating_constraint():
    from apps.testimonials.models import Testimonial
    with pytest.raises(IntegrityError):
        Testimonial.objects.create(author_name="X", quote="q", rating=9)


def test_newsletter_token_autogenerated():
    from apps.newsletter.models import Subscriber
    s = Subscriber.objects.create(email="n@x.com")
    assert s.confirm_token and len(s.confirm_token) > 20
