# Generated by Django 5.1.6 on 2026-06-10 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='opening',
            field=models.ForeignKey(blank=True, help_text='Null = speculative application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='careers.jobopening'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', '-created_at'], name='careers_job_status_13e14c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['opening'], name='careers_job_opening_0954c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('terms_accepted', True)), name='application_terms_required'),
        ),
    ]
