from __future__ import annotations

from django.contrib import admin

from .models import Lead, LeadNote


class LeadNoteInline(admin.TabularInline):
    model = LeadNote
    extra = 1
    readonly_fields = ("author", "created_at")

    def save_model(self, request, obj, form, change):  # pragma: no cover
        if not obj.author_id:
            obj.author = request.user
        super().save_model(request, obj, form, change)


@admin.register(Lead)
class LeadAdmin(admin.ModelAdmin):
    list_display = ("name", "email", "status", "source", "assigned_to", "created_at")
    list_filter = ("status", "source", "created_at")
    search_fields = ("name", "email", "phone", "message")
    autocomplete_fields = ("assigned_to",)
    date_hierarchy = "created_at"
    inlines = [LeadNoteInline]
    readonly_fields = ("name", "email", "phone", "message", "source", "spam_score",
                       "ip_address", "user_agent", "created_at", "updated_at")
    fields = ("status", "assigned_to", *readonly_fields)

    def has_add_permission(self, request) -> bool:
        # Leads are system-generated by the contact form.
        return False

    def save_formset(self, request, form, formset, change):
        instances = formset.save(commit=False)
        for instance in instances:
            if isinstance(instance, LeadNote) and not instance.author_id:
                instance.author = request.user
            instance.save()
        formset.save_m2m()
