# Generated by Django 5.1.6 on 2026-06-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
