# Generated by Django 5.1.6 on 2026-06-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, db_index=True, max_length=512, null=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=180)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary large image')], default='summary_large_image', max_length=20)),
                ('robots_directives', models.CharField(blank=True, default='index,follow', max_length=120)),
                ('schema_jsonld', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.media')),
            ],
            options={
                'verbose_name': 'SEO metadata',
                'verbose_name_plural': 'SEO metadata',
                'constraints': [models.UniqueConstraint(condition=models.Q(('object_id__isnull', False)), fields=('content_type', 'object_id'), name='uniq_seo_per_object')],
            },
        ),
    ]
