# Generated by Django 6.0.6 on 2026-07-07 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.PositiveIntegerField(default=0)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='blurb',
            field=models.TextField(blank=True, help_text='Short description for the disciplines section.'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media'),
        ),
    ]
