# Generated by Django 6.0.6 on 2026-07-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stat_projectcategory_blurb_projectcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional slide title / caption', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.media')),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
